### ISSUE TITLE
better s3_get_files message

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/s3#8]
`s3_get_files` first checks all file sizes and asks the user if it is okay to download all these files with a total file size; however, some of these files could already exist locally.  Although the underlying use of `s3_get` does prevent the redownloading of these files, the initial message from `s3_get_files` still states that they will be downloaded.

We should refactor `s3_get_files` to check for all files first, then announce which files do and do not exist and request to download only those that do not exist.

**Comment by erikarasnick** [comment]
I meant to do this as a pull request. oops. Not sure if this is the best way to do this.. lots of repetition between s3_get and s3_get_files now.
