### ISSUE TITLE
different public files for testing

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/s3#9]
s3://1000genomes/README.analysis_history

**Comment by erikarasnick** [comment]
Should I use this exact file? I think it's a text file.

**Comment by cole-brokamp** [comment]
Yes, I think that it will be a good one because it will always be there and it is a small file. But let's use this in addition to the other files that we are using in our tests.  We can keep the ones we have in the README and examples, but I just wanted to write more tests using this one.
